
language: python

cache:
  directories:
    - $HOME/.cache/pip

services:
  - postgresql
before_script:
  - psql -c 'create database django_webtest_tests;' -U postgres

install:
  - pip install tox
script:
  - tox
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django111-std
    - python: "2.7"
      env: TOXENV=py27-django111-clocale
    - python: "2.7"
      env: TOXENV=py27-django111-postgres
    - python: "3.5"
      env: TOXENV=py35-django111-std
    - python: "3.5"
      env: TOXENV=py35-django111-clocale
    - python: "3.5"
      env: TOXENV=py35-django111-postgres
    - python: "3.5"
      env: TOXENV=py35-django21-std
    - python: "3.5"
      env: TOXENV=py35-django21-clocale
    - python: "3.5"
      env: TOXENV=py35-django21-postgres
    - python: "3.5"
      env: TOXENV=py35-django22-std
    - python: "3.5"
      env: TOXENV=py35-django22-clocale
    - python: "3.5"
      env: TOXENV=py35-django22-postgres
    - python: "3.6"
      env: TOXENV=py36-django111-std
    - python: "3.6"
      env: TOXENV=py36-django111-clocale
    - python: "3.6"
      env: TOXENV=py36-django111-postgres
    - python: "3.6"
      env: TOXENV=py36-django21-std
    - python: "3.6"
      env: TOXENV=py36-django21-clocale
    - python: "3.6"
      env: TOXENV=py36-django21-postgres
    - python: "3.6"
      env: TOXENV=py36-django22-std
    - python: "3.6"
      env: TOXENV=py36-django22-clocale
    - python: "3.6"
      env: TOXENV=py36-django22-postgres
